In [1]:
from getpass import getpass
token = getpass('Enter GitHub token: ')

username = 'mim-1999'
repo = 'customer-churn-prediction'
!git clone https://{token}@github.com/{username}/{repo}.git
%cd customer-churn-prediction
!git pull origin main --no-rebase --no-edit

Enter GitHub token: ··········
Cloning into 'customer-churn-prediction'...
remote: Enumerating objects: 38, done.
remote: Counting objects: 100% (38/38), done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 38 (delta 10), reused 12 (delta 4), pack-reused 0 (from 0)
Receiving objects: 100% (38/38), 272.73 KiB | 7.37 MiB/s, done.
Resolving deltas: 100% (10/10), done.
/content/customer-churn-prediction
From https://github.com/mim-1999/customer-churn-prediction
 * branch            main       -> FETCH_HEAD
Already up to date.

In [2]:
import pandas as pd

url = 'https://raw.githubusercontent.com/mim-1999/customer-churn-prediction/main/data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv'
df = pd.read_csv(url)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [4]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [5]:
df.nunique()

customerID          7043
gender                 2
SeniorCitizen          2
Partner                2
Dependents             2
tenure                73
PhoneService           2
MultipleLines          3
InternetService        3
OnlineSecurity         3
OnlineBackup           3
DeviceProtection       3
TechSupport            3
StreamingTV            3
StreamingMovies        3
Contract               3
PaperlessBilling       2
PaymentMethod          4
MonthlyCharges      1585
TotalCharges        6531
Churn                  2
dtype: int64

In [6]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df['TotalCharges'] = df['TotalCharges'].fillna(0)

In [7]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges  TotalCharges
count    7043.000000  7043.000000     7043.000000   7043.000000
mean        0.162147    32.371149       64.761692   2279.734304
std         0.368612    24.559481       30.090047   2266.794470
min         0.000000     0.000000       18.250000      0.000000
25%         0.000000     9.000000       35.500000    398.550000
50%         0.000000    29.000000       70.350000   1394.550000
75%         0.000000    55.000000       89.850000   3786.600000
max         1.000000    72.000000      118.750000   8684.800000

In [8]:
df['TotalCharges'].dtype

dtype('float64')

In [9]:
df = df.drop('customerID', axis=1)

In [10]:
df.nunique().sort_values()

gender                 2
SeniorCitizen          2
Partner                2
Dependents             2
PhoneService           2
PaperlessBilling       2
Churn                  2
InternetService        3
TechSupport            3
OnlineSecurity         3
DeviceProtection       3
OnlineBackup           3
StreamingMovies        3
StreamingTV            3
Contract               3
MultipleLines          3
PaymentMethod          4
tenure                73
MonthlyCharges      1585
TotalCharges        6531
dtype: int64

In [11]:
df['OnlineSecurity'].unique()

array(['No', 'Yes', 'No internet service'], dtype=object)

In [12]:
df['MultipleLines'].unique()

array(['No phone service', 'No', 'Yes'], dtype=object)

In [13]:
cols_to_simplify = ['OnlineSecurity', 'TechSupport', 'OnlineBackup',
                     'DeviceProtection', 'StreamingTV', 'StreamingMovies']
for col in cols_to_simplify:
    df[col] = df[col].replace('No internet service', 'No')

In [14]:
df['MultipleLines'] = df['MultipleLines'].replace('No phone service', 'No')

In [15]:
df['MultipleLines'].unique()

array(['No', 'Yes'], dtype=object)

In [16]:
df['SeniorCitizen'].unique()

array([0, 1])

In [17]:
df['gender'] = df['gender'].map({'Male': 0, 'Female': 1})
df['Partner'] = df['Partner'].map({'Yes': 1, 'No': 0})
df['Dependents'] = df['Dependents'].map({'Yes': 1, 'No': 0})
df['PhoneService'] = df['PhoneService'].map({'Yes': 1, 'No': 0})
df['PaperlessBilling'] = df['PaperlessBilling'].map({'Yes': 1, 'No': 0})
df['Churn'] = df['Churn'].map({'Yes': 1, 'No': 0})

In [18]:
df[['gender','Partner','Dependents','PhoneService','PaperlessBilling','Churn','SeniorCitizen']].dtypes

gender              int64
Partner             int64
Dependents          int64
PhoneService        int64
PaperlessBilling    int64
Churn               int64
SeniorCitizen       int64
dtype: object

In [19]:
df.nunique().sort_values()

gender                 2
SeniorCitizen          2
Partner                2
Dependents             2
PhoneService           2
MultipleLines          2
OnlineBackup           2
OnlineSecurity         2
StreamingTV            2
StreamingMovies        2
DeviceProtection       2
TechSupport            2
PaperlessBilling       2
Churn                  2
Contract               3
InternetService        3
PaymentMethod          4
tenure                73
MonthlyCharges      1585
TotalCharges        6531
dtype: int64

In [20]:
binary_cols = ['MultipleLines', 'OnlineBackup', 'OnlineSecurity', 'StreamingTV',
               'StreamingMovies', 'DeviceProtection', 'TechSupport']
for col in binary_cols:
    df[col] = df[col].map({'Yes': 1, 'No': 0})

In [21]:
df.nunique().sort_values()

gender                 2
SeniorCitizen          2
Partner                2
Dependents             2
PhoneService           2
MultipleLines          2
OnlineBackup           2
OnlineSecurity         2
StreamingTV            2
StreamingMovies        2
DeviceProtection       2
TechSupport            2
PaperlessBilling       2
Churn                  2
Contract               3
InternetService        3
PaymentMethod          4
tenure                73
MonthlyCharges      1585
TotalCharges        6531
dtype: int64

In [25]:
df = pd.get_dummies(df, columns=['Contract', 'InternetService', 'PaymentMethod'], drop_first=False)

In [26]:
df.shape

(7043, 27)

In [27]:
df.columns.tolist()

['gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'tenure',
 'PhoneService',
 'MultipleLines',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'PaperlessBilling',
 'MonthlyCharges',
 'TotalCharges',
 'Churn',
 'Contract_Month-to-month',
 'Contract_One year',
 'Contract_Two year',
 'InternetService_DSL',
 'InternetService_Fiber optic',
 'InternetService_No',
 'PaymentMethod_Bank transfer (automatic)',
 'PaymentMethod_Credit card (automatic)',
 'PaymentMethod_Electronic check',
 'PaymentMethod_Mailed check']

In [29]:
df.dtypes.value_counts()

int64      15
bool       10
float64     2
Name: count, dtype: int64

In [31]:
df.to_csv('data/processed/telco_clean.csv', index=False)